<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/UsrYachtRentals/Schemas/UsrTrafficLight/UsrTrafficLight.cs" Condition="Exists('$(PkgPath)/UsrYachtRentals/Schemas/UsrTrafficLight/UsrTrafficLight.cs')" />
		<Compile Include="$(PkgPath)/UsrYachtRentals/Schemas/UsrVwContactAgeDays/UsrVwContactAgeDays.cs" Condition="Exists('$(PkgPath)/UsrYachtRentals/Schemas/UsrVwContactAgeDays/UsrVwContactAgeDays.cs')" />
		<Compile Include="$(PkgPath)/UsrYachtRentals/Schemas/UsrYachtDriveTypes/UsrYachtDriveTypes.cs" Condition="Exists('$(PkgPath)/UsrYachtRentals/Schemas/UsrYachtDriveTypes/UsrYachtDriveTypes.cs')" />
		<Compile Include="$(PkgPath)/UsrYachtRentals/Schemas/UsrYachts/UsrYachts.cs" Condition="Exists('$(PkgPath)/UsrYachtRentals/Schemas/UsrYachts/UsrYachts.cs')" />
		<Compile Include="$(PkgPath)/UsrYachtRentals/Schemas/UsrYachtStatuses/UsrYachtStatuses.cs" Condition="Exists('$(PkgPath)/UsrYachtRentals/Schemas/UsrYachtStatuses/UsrYachtStatuses.cs')" />
	</ItemGroup>
</Project>